version: '3.0'

services:
  auth1:
    build: .
    container_name: auth-microservice-container1
    env_file:
      - .env
    networks:
      - geo-net
  auth2:
    build: .
    container_name: auth-microservice-container2
    env_file:
      - .env
    networks:
      - geo-net
  auth3:
    build: .
    container_name: auth-microservice-container3
    env_file:
      - .env
    networks:
      - geo-net
  auth-nginx:
    image: nginx
    ports:
      - "1235:1235"
    volumes:
      - ./auth-nginx.conf:/etc/nginx/nginx.conf
    networks:
      - geo-net
    depends_on:
      - auth1
      - auth2
      - auth3

networks:
  geo-net:
    external: true 
    name: geo-net